#!/bin/sh
PREREQ=""
prereqs()
 {
     echo "$PREREQ"
 }
case $1 in
 prereqs)
     prereqs
     exit 0
     ;;
esac
. /usr/share/initramfs-tools/hook-functions
copy_exec /usr/bin/tpm2_startauthsession
copy_exec /usr/bin/tpm2_policypcr
copy_exec /usr/bin/tpm2_policyauthorize
copy_exec /usr/bin/tpm2_unseal
copy_exec /usr/bin/tpm2_flushcontext
exit 0
